# Generated by Django 5.2.6 on 2025-09-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0003_remove_post_images_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
