# Generated by Django 5.2.6 on 2025-09-13 16:11

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(help_text='Title of the task', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional task description', null=True)),
                ('completed', models.BooleanField(default=False, help_text='Whether the task is completed')),
                ('due_date', models.DateTimeField(blank=True, help_text='Optional task due date', null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Task priority', max_length=10)),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['due_date'], name='todos_todo_due_dat_f2739d_idx'), models.Index(fields=['priority'], name='todos_todo_priorit_93f987_idx'), models.Index(fields=['completed'], name='todos_todo_complet_334461_idx')],
            },
        ),
    ]
